/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CensorWords {
    }
}
declare global {
    interface HTMLCensorWordsElement extends Components.CensorWords, HTMLStencilElement {
    }
    var HTMLCensorWordsElement: {
        prototype: HTMLCensorWordsElement;
        new (): HTMLCensorWordsElement;
    };
    interface HTMLElementTagNameMap {
        "censor-words": HTMLCensorWordsElement;
    }
}
declare namespace LocalJSX {
    interface CensorWords {
    }
    interface IntrinsicElements {
        "censor-words": CensorWords;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "censor-words": LocalJSX.CensorWords & JSXBase.HTMLAttributes<HTMLCensorWordsElement>;
        }
    }
}
